apiVersion: v1
kind: Service
metadata:
  name: my-app
  labels:
    app: my-app

spec:
  type: NodePort
  ports:
  - port: 8080
    protocol: TCP
    targetPort: 8080
  selector:
    app: my-app

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: my-app
  labels:
    app: my-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: my-app
  template:
    metadata:
      labels:
        app: my-app
    spec:
      containers:
      - name: springboot
        image: sreelk589/sonar-demo: {{.Values.tag_name}}
        imagePullPolicy: Always
        ports:
        - containerPort: 8080
